/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        amber: { DEFAULT: '#F5B800', deep: '#D9A400' },
        'amber-ink': '#6B4E00',
        espresso: '#171512',
        crema: '#FBF7EF',
        go: '#2F6B3A',
        success: { DEFAULT: '#2F6B3A', ink: { DEFAULT: '#23522C', dark: '#7FCE8C' } },
        danger: {
          DEFAULT: '#B3261E',
          tint: '#FBE6E3',
          ink: { DEFAULT: '#8F1E17', dark: '#FF9285' },
        },
        clay: { DEFAULT: '#963E13', bright: '#C0501B' },
        bg: { DEFAULT: 'var(--color-bg)', shell: 'var(--color-bg-shell)' },
        surface: { DEFAULT: 'var(--color-surface)', sunken: 'var(--color-surface-sunken)' },
        border: { DEFAULT: 'var(--color-border)', input: 'var(--color-border-input)' },
        text: {
          DEFAULT: 'var(--color-text)',
          muted: 'var(--color-text-muted)',
          subtle: 'var(--color-text-subtle)',
        },
        'on-brand': 'var(--color-on-brand)',
        'on-success': '#FFFFFF',
        focus: { ring: 'var(--color-focus-ring)', halo: 'var(--color-focus-halo)' },
        'status-neutral': 'var(--color-status-neutral)',
        frame: {
          bg: '#171512',
          text: '#FFFFFF',
          'text-muted': '#C9C2B2',
          border: 'rgba(255, 255, 255, 0.14)',
          'chip-bg': '#2C2822',
          'chip-border': 'rgba(255, 255, 255, 0.10)',
          'active-bg': 'rgba(245, 184, 0, 0.16)',
        },
      },
      fontFamily: {
        display: ['var(--font-display)', 'Georgia', 'serif'],
        body: ['var(--font-body)', 'system-ui', 'sans-serif'],
        mono: ['var(--font-mono)', 'ui-monospace', 'SFMono-Regular', 'Menlo', 'monospace'],
      },
      fontSize: {
        hero: [
          'clamp(1.75rem, 1.3rem + 2vw, 2.5rem)',
          { lineHeight: '1.05', fontWeight: '800', letterSpacing: '-0.03em' },
        ],
        display: ['28px', { lineHeight: '31px', fontWeight: '800', letterSpacing: '-0.02em' }],
        title: ['17px', { lineHeight: '22px', fontWeight: '700' }],
        lede: ['16px', { lineHeight: '26px', fontWeight: '400' }],
        eyebrow: ['11px', { lineHeight: '16px', fontWeight: '600', letterSpacing: '0.09em' }],
        btn: ['14px', { lineHeight: '20px', fontWeight: '600' }],
        body: ['15px', { lineHeight: '22px' }],
        small: ['13px', { lineHeight: '18px' }],
        'table-header': [
          '11px',
          { lineHeight: '16px', fontWeight: '600', letterSpacing: '0.09em' },
        ],
      },
      spacing: {
        'row-sm': '32px',
        'row-md': '40px',
        'row-lg': '48px',
        tap: '44px',
        'tap-compact': '36px',
      },
      borderRadius: { xs: '12px', sm: '14px', md: '18px', lg: '20px', item: '14px', tile: '11px' },
      boxShadow: {
        'overlay-sm': '0 2px 8px rgba(23, 21, 18, 0.14)',
        'overlay-lg': '0 12px 32px rgba(23, 21, 18, 0.22)',
        'brand-halo': '0 0 0 4px rgba(245, 184, 0, 0.24)',
      },
    },
  },
  plugins: [],
};
