export const RATES_COPY = {
  eyebrow: 'Plataforma',
  nav: 'Tarifas',
  title: 'Tarifas',
  subtitle: (unofficialCount: number): string =>
    unofficialCount === 0
      ? 'Todas las tarifas son oficiales'
      : `${unofficialCount} sin tarifa oficial`,
  official: 'Oficial',
  unofficial: 'No oficial',
  noFare: 'Sin tarifa',
  refresh: 'Actualizar',
  filterByMark: 'Filtrar por marca',
  markFilters: { all: 'Todas', unofficial: 'No oficial', official: 'Oficial' },
  columns: {
    municipality: 'Municipio',
    service: 'Servicio',
    base: 'Base',
    surcharges: 'Recargos',
    mark: 'Marca',
    validFrom: 'Vigente desde',
    companies: 'Empresas',
    coverage: 'Cobertura',
    actions: 'Acciones',
  },
  surchargesCell: (night: number, holiday: number): string =>
    `Noct. ${night.toLocaleString('es-CO')} % · Fest. ${holiday.toLocaleString('es-CO')} %`,
  activeCompanies: (count: number): string => `${count} ${count === 1 ? 'activa' : 'activas'}`,
  view: 'Ver',
  viewAria: (municipality: string, service: string): string =>
    `Ver la tarifa de ${service} en ${municipality}`,
  loadingList: 'Cargando tarifas',
  emptyList: 'Aún no hay municipios con empresas activas.',
  emptyListHint: 'Las tarifas aparecen cuando apruebas la primera empresa de un municipio.',
  emptyFilter: 'Ninguna tarifa coincide con el filtro.',
  showAll: 'Ver todas',
  listError: 'No pudimos cargar las tarifas.',
  offlineList: 'Sin conexión · la lista puede estar desactualizada.',
  offlineData: 'Sin conexión · los datos pueden estar desactualizados.',
  offlineSave: 'Sin conexión · no se puede guardar ahora.',
  backToList: 'Volver a Tarifas',
  detailEyebrow: 'Plataforma · Tarifas',
  detailTitle: (municipality: string, service: string): string => `${municipality} · ${service}`,
  detailSubtitle: (department: string, validFrom: string, author: string | null): string =>
    `${department} · vigente desde el ${validFrom}${author ? ` · cambió ${author}` : ''}`,
  loadingDetail: 'Cargando tarifa',
  detailError: 'No pudimos cargar la tarifa.',
  notFound: 'Esta tarifa ya no existe.',
  unofficialNotice: (municipality: string): string =>
    `Esta tarifa es provisional. Todavía no se ha cargado la tarifa oficial de la Alcaldía de ${municipality}.`,
  reference: (reference: string): string => `Referencia: ${reference}`,
  noFareNotice:
    'Este municipio todavía no tiene tarifa. Se crea al aprobar la primera empresa del servicio; mientras tanto solo puedes editar los parámetros.',
  platformDefault: 'Valor por defecto de la plataforma',
  usedByTitle: 'Quién la usa',
  usedBy: (count: number, municipality: string): string =>
    `Aplica a las solicitudes nuevas de ${count === 1 ? 'la empresa activa' : `las ${count} empresas activas`} de ${municipality}.`,
  edit: 'Editar valores',
  review: 'Revisar y guardar',
  discard: 'Descartar cambios',
  discardConfirmTitle: '¿Descartar los cambios?',
  discardConfirmBody: 'Vas a perder los valores que modificaste.',
  discardConfirmKeep: 'Seguir editando',
  leaveTitle: '¿Salir sin guardar?',
  leaveBody: 'Tienes cambios sin guardar. Si sales, se pierden.',
  leaveConfirm: 'Salir',
  leaveStay: 'Seguir editando',
  effectiveNow: 'Vigente desde hoy, al guardar.',
  modified: 'Modificado',
  markTitle: 'Marca de esta versión',
  markQuestion: '¿Esta es la tarifa oficial de la Alcaldía?',
  markUnofficial: 'No oficial',
  markUnofficialHelp: 'Provisional, hasta que llegue la tarifa de la Alcaldía.',
  markOfficial: 'Oficial',
  markOfficialHelp: 'Fijada por un acto de la Alcaldía.',
  referenceLabel: 'Referencia del acto (opcional)',
  referenceHint: 'Ej.: número y fecha del acto.',
  referenceInvalid: (min: number, max: number): string =>
    `Escribe entre ${min} y ${max} caracteres.`,
  confirmTitle: '¿Guardar la nueva versión de la tarifa?',
  confirmScope: (count: number, municipality: string): string =>
    `Aplica a las solicitudes nuevas de ${count} ${count === 1 ? 'empresa' : 'empresas'} de ${municipality}.`,
  confirmKeep: 'Los viajes ya pedidos y las cotizaciones vigentes conservan su total.',
  confirmMarkOnly: 'Este cambio no modifica los valores.',
  confirmBefore: 'Antes',
  confirmAfter: 'Ahora',
  save: 'Guardar versión',
  saving: 'Guardando…',
  keepEditing: 'Seguir editando',
  saved: 'Tarifa actualizada · aplica a las solicitudes nuevas.',
  markedOfficial: 'Marcada como oficial.',
  saveFailed: 'No pudimos guardar los cambios. Inténtalo de nuevo.',
  partialSave: (detail: string): string =>
    `Se guardó una parte de los cambios, pero no todo. ${detail}`,
  conflict: (version: number, author: string | null): string =>
    `Alguien más cambió esta tarifa mientras editabas (versión ${version}${author ? `, por ${author}` : ''}).`,
  conflictTitle: 'La tarifa cambió mientras editabas',
  compare: 'Comparar con mis cambios',
  useMine: 'Usar mis valores',
  discardMine: 'Descartar mis cambios',
  currentValues: 'Valores actuales',
  yourChanges: 'Tus cambios',
  outOfRange: (min: string, max: string): string =>
    `Este valor está fuera del rango permitido (${min} a ${max}).`,
  outOfRangeServer: 'Este valor está fuera del rango permitido.',
  searchAboveExpansion: 'El radio de búsqueda no puede superar el radio de expansión.',
  history: 'Historial',
  fareHistory: 'Historial de la tarifa',
  paramsHistory: 'Historial de los parámetros',
  current: 'Vigente',
  initialVersion: 'Versión inicial',
  originMigrated: (company: string | null): string =>
    company ? `Migración de la tarifa de ${company}` : 'Migración de la configuración anterior',
  originCompanyApproval: (company: string | null): string =>
    company ? `Creada al aprobar a ${company}` : 'Creada al aprobar a una empresa',
  originUnknown: 'Sin autor registrado',
  historyEmpty: 'Todavía no hay versiones.',
  historyError: 'No pudimos cargar el historial.',
  loadOlder: 'Ver versiones anteriores',
  loadingOlder: 'Cargando…',
  sectionLabels: {
    fareMark: 'Marca',
  },
} as const;
