import { endSentence } from '../lib/text';

export const SETTLEMENT_MONTHS_SHORT = [
  'ene',
  'feb',
  'mar',
  'abr',
  'may',
  'jun',
  'jul',
  'ago',
  'sep',
  'oct',
  'nov',
  'dic',
] as const;

export const SETTLEMENT_MONTHS_LONG = [
  'enero',
  'febrero',
  'marzo',
  'abril',
  'mayo',
  'junio',
  'julio',
  'agosto',
  'septiembre',
  'octubre',
  'noviembre',
  'diciembre',
] as const;

export const SETTLEMENT_WEEKDAYS = [
  'domingo',
  'lunes',
  'martes',
  'miércoles',
  'jueves',
  'viernes',
  'sábado',
] as const;

export const SETTLEMENT_COPY = {
  nav: 'Conciliación',
  eyebrow: 'Conciliación',
  fallbackTitle: 'Conciliación semanal',
  weekTitle: (range: string): string => `Semana del ${range}`,
  rangeTitle: (range: string): string => `Del ${range}`,
  downloadCsv: 'Descargar CSV',
  downloadBusy: 'Preparando archivo…',
  printAction: 'Imprimir',
  controlsLabel: 'Controles del reporte',
  previousWeek: '‹ Semana anterior',
  nextWeek: 'Semana siguiente ›',
  lastWeek: 'Semana pasada',
  thisWeek: 'Esta semana (en curso)',
  otherRange: 'Otro rango',
  from: 'Desde',
  to: 'Hasta',
  rangeHelper: 'Máximo 31 días. Para registrar remisiones elige una semana de lunes a domingo.',
  generate: 'Generar reporte',
  generating: 'Generando…',
  driverFilter: 'Conductor',
  allDrivers: 'Todos los conductores',
  generatedAt: (value: string): string => `Generado el ${value} (hora de Bogotá)`,
  inProgressBadge: 'Semana en curso',
  inProgressNote: 'Las cifras pueden cambiar.',
  rangeChanged: 'Cambiaste el rango. Genera el reporte para verlo.',
  stats: {
    ariaLabel: 'Resumen de la conciliación',
    trips: 'Viajes',
    cash: 'Efectivo cobrado',
    commission: 'Comisión registrada',
    toRemit: 'Total a remitir',
    driverNet: 'Neto de conductores',
    pending: 'Cobros pendientes',
  },
  pendingNotice: (count: number, amount: string): string =>
    `Hay ${count} ${count === 1 ? 'viaje' : 'viajes'} con cobro pendiente por ${amount}. No suman al total a remitir hasta que el conductor confirme el efectivo.`,
  pendingStat: (count: number, amount: string): string => `${count} · ${amount}`,
  caption: (range: string): string => `Conciliación por conductor ${range}`,
  columns: {
    driver: 'Conductor',
    trips: 'Viajes',
    cash: 'Efectivo cobrado',
    commission: 'Comisión registrada',
    driverNet: 'Neto del conductor',
    toRemit: 'Total a remitir',
    pending: 'Cobros pendientes',
    remittance: 'Remisión',
  },
  totals: 'Totales',
  pendingBadge: 'Pendiente',
  pendingPrint: 'Cobro pendiente',
  noPending: '—',
  loadingLabel: 'Generando el reporte',
  announceDone: (drivers: number, amount: string): string =>
    `Reporte generado: ${drivers} ${drivers === 1 ? 'conductor' : 'conductores'}, total a remitir ${amount}.`,
  announceWeek: (label: string): string => `Semana seleccionada: ${label}.`,
  empty: {
    title: 'No hay viajes registrados en ese rango.',
    description: 'Prueba con otra semana.',
    filteredTitle: 'Este conductor no tiene viajes en ese rango.',
    filteredAction: 'Ver todos los conductores',
  },
  error: {
    title: 'No pudimos generar el reporte.',
    offlineTitle: 'Sin conexión.',
    forbidden: 'No tienes acceso a esta pantalla.',
    staleOffline: (value: string): string =>
      endSentence(`Sin conexión. Estás viendo el reporte generado el ${value}`),
    offlineHint: 'Sin conexión: esta acción no está disponible ahora.',
  },
  range: {
    invalidDate: 'Escribe una fecha válida.',
    fromAfterTo: 'La fecha inicial no puede ser posterior a la final.',
    tooLong: 'El rango no puede superar 31 días.',
  },
  csv: {
    success: (filename: string): string => `Descargamos ${filename}.`,
    error: 'No pudimos descargar el archivo. No se guardó nada.',
    offline: 'Sin conexión: no se descargó el archivo.',
    forbidden: 'No tienes permiso para descargar este reporte.',
    retry: 'Reintentar',
    fallbackName: (from: string, to: string): string => `conciliacion_${from}_${to}.csv`,
  },
  remittance: {
    none: 'Sin remitir',
    remitted: (amount: string, date: string): string => `Remitido ${amount} · ${date}`,
    remittedNoDate: (amount: string): string => `Remitido ${amount}`,
    partial: (amount: string, balance: string): string =>
      `Remitido ${amount} · saldo por remitir ${balance}`,
    mark: 'Marcar como remitido',
    markAria: (name: string): string => `Marcar como remitido: ${name}`,
    markBalance: (balance: string): string => `Marcar saldo ${balance}`,
    history: 'Historial',
    historyAria: (name: string): string => `Historial de remisiones de ${name}`,
    weekOpen: 'La semana aún no termina',
    dialogTitle: 'Marcar como remitido',
    dialogBody: (name: string, amount: string, range: string): string =>
      `Vas a registrar que ${name} remitió ${amount} de comisión de la semana del ${range}.`,
    dialogAudit:
      'Queda guardado con tu nombre y la fecha de hoy. Si te equivocas, puedes deshacerlo: el registro original se conserva.',
    confirm: 'Marcar como remitido',
    confirming: 'Registrando…',
    cancel: 'Cancelar',
    refreshReport: 'Actualizar reporte',
    success: (name: string, amount: string): string => `Marcado como remitido: ${name}, ${amount}.`,
    idempotent: 'Esta semana ya estaba marcada como remitida.',
    balanceChanged:
      'El saldo cambió mientras mirabas la pantalla. Actualiza el reporte y vuelve a intentar.',
    weekInProgress: 'La semana aún no termina. Podrás marcarla como remitida desde el lunes.',
    nothingToRemit: 'Esta semana ya no tiene nada por remitir.',
    driverNotFound: 'Este conductor ya no existe en tu empresa.',
    offline: 'Sin conexión: no se registró nada. Inténtalo cuando vuelva la señal.',
    error: 'No pudimos registrar la remisión. No se guardó nada. Inténtalo de nuevo.',
  },
  history: {
    title: (name: string): string => `Remisiones de ${name}`,
    entryRemittance: (amount: string): string => `Remisión · ${amount}`,
    entryReversal: (amount: string): string => `Reversión · ${amount}`,
    recordedBy: (date: string, name: string): string => `${date} · por ${name}`,
    weekOf: (range: string): string => `Semana del ${range}`,
    undo: 'Deshacer',
    empty: 'Sin remisiones registradas.',
    error: 'No pudimos cargar el historial.',
    undoTitle: '¿Deshacer la remisión?',
    undoBody: (name: string, amount: string): string =>
      `Se registrará que ${name} aún no remitió ${amount} de esa semana. El registro original no se borra: queda en el historial.`,
    undoConfirm: 'Deshacer remisión',
    undoing: 'Deshaciendo…',
    undoSuccess: (amount: string): string => `Remisión deshecha: ${amount}.`,
    notReversible: 'Esta remisión ya no se puede deshacer.',
    notFound: 'No encontramos esa remisión. Actualiza el historial.',
    undoOffline: 'Sin conexión: no se deshizo nada. Inténtalo cuando vuelva la señal.',
    undoError: 'No pudimos deshacer la remisión. No se guardó nada. Inténtalo de nuevo.',
  },
  print: {
    heading: 'VoyYa · Conciliación semanal',
    period: (from: string, to: string): string => `Del ${from} al ${to} (hora de Bogotá)`,
    generated: (value: string): string => `Generado el ${value}`,
    partial: 'Semana en curso: cifras parciales',
    footer: 'Documento con datos personales (cédula). Uso interno de la empresa.',
  },
} as const;
